### ISSUE TITLE
Team Assignments - Accept notification and button

### ISSUE THREAD

**Issue by ahillbilly** [ChasmSolutions/disciple-tools#53]
I assigned a contact to Himayrunner and the accept notification and button showed up. 

I assigned a contact to Team 1 and the contact showed up in the list but the accept button at the top did not show up and I couldn't figure out how you'd accept a team contact personally.

**Comment by ChrisChasm** [comment]
Thanks for the issue. This is a good way for us to keep working on these things. Regarding the Team part, I haven't built he "all team" accept feature yet like we talked about. So we can leave this ticket open until I get to it. I'm working on the profiles first, because they will be a key controller of the dashboard. So they are a little upstream from the intimation piece at the moment.

**Comment by ChrisChasm** [comment]
I believe this issue is slightly regarding and older interface and I believe the conversation and decision has progressed here https://github.com/ChasmSolutions/disciple-tools/issues/155 and here https://github.com/ChasmSolutions/disciple-tools/issues/149
